# Workflow executed on "release" events.
name: release

on:
  release:
    types: [published]

jobs:

  # Deploy to Github Packages.
  deploy:
    name: Deploy to Github Packages

    runs-on: ubuntu-latest

    container:
      image: maven:3.6-alpine

    steps:

      # Retrieve the code from Github.
      - uses: actions/checkout@v2

      - name: Publish to GitHub Packages.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -e --settings maven-settings.xml deploy:deploy-file -DrepositoryId='github_openaims' -DpomFile='pom.xml' -Dfile='jar/log4j-1.2.17-aims.jar'
